# yaml-language-server: $schema=https://raw.githubusercontent.com/softprops/github-actions-schemas/master/workflow.json
name: CI (JS)

on:
  push:
    branches: ["main"]
    paths:
      - '**/*.js'
      - '**/*.html'
      - '**/*.css'
  pull_request:
    branches: ["main"]
    paths:
      - '**/*.js'
      - '**/*.html'
      - '**/*.css'
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Format (JS)
        uses: actionsx/prettier@v2
        with:
          args: --check .
