# yaml-language-server: $schema=https://raw.githubusercontent.com/softprops/github-actions-schemas/master/workflow.json
name: CI (python)

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.py"
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.py"
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip" # caching pip dependencies
      - name: Install linters
        run: pip install pylint==2.17.5 black==23.7.0
      - name: Lint
        run: pylint friends_queue
      - name: Check formatting
        run: black --check friends_queue
