# yaml-language-server: $schema=https://raw.githubusercontent.com/softprops/github-actions-schemas/master/workflow.json
name: CI (python)

on:
  push:
    branches: ["main"]
    paths:
      - '**/*.py'
  pull_request:
    branches: ["main"]
    paths:
      - '**/*.py'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint and format
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: friends_queue
          use-pylint: true
          use-black: true
